- integrationServer/package.json
- integrationServer/requestHandlers.js
- integrationServer/routes.js
- integrationServer/server.js
- integrationServer/spec/serverSpec.js
Still need to test response object once we finalize what that will look like
> (feature) Backend: create Integration server (Closes #3)

- client/package.json
- client/src/App.jsx
- client/src/Nav.jsx
Laid out logic to send GET request to server on user submit.
Still need to determine how the response object (directions with the risk factors) will be displayed (e.g. what component we will pass it to) 
**_TLDR: There is currently no code to handle the response object_**
> (feature) Send GET request on user submit (Closes #25)

- client/src/components/App/App.jsx
Still need to show pin before it is set. Will write out logic in a separate branch
> (feature) Set destination pin on user submit (Closes #16)

- client/src/components/App/App.jsx
Currently, the App and Direction components are configured to only display regular Google Maps direction data. This is for testing purposes. We will need to modify the prop being passed into the Direction component to be in the correct format for production.
> (feature) Modify App component to make requests to integration server (Closes #51)

- tripServer/requestHandlers.js
- tripServer/spec/helperSpec.js
- tripServer/spec/serverSpec.js
- tripServer/tripHelpers.js
Processes directions object to generate array of coordinates separated by distance lower than set threshold.
Still to do:
-configure request handler to accept directions query.
> Feature/riskservice (Closes #31)

- client/src/components/App/App.jsx
- client/src/components/Direction/Direction.jsx
Also, comment out componentWillMount in Direction component.
> (fix) Modify expected Integration Server response format (Closes #55)

- tripServer/spec/helperSpec.js
- tripServer/spec/specData.js
Refactored test suite for easier readability.
Added more robustness to tests.
> (refactor) Refactored Trip Server test suite for easier readability

- client/src/components/App/App.jsx
- client/src/components/Direction/Direction.jsx
- client/src/components/utils/utils.js
The 'B' (destination) marker that is auto-generated by google maps is currently not showing. We can work on getting it to display if we end up needing it.
> (fix) Render directions object from server (Closes #59)

- tripServer/requestHandlers.js
Trip server previously had origin and destination hard coded.
> (fix) Utilize directions request passed on from Integration server

- tripServer/spec/serverSpec.js
- tripServer/tripHelpers.js
Added more thorough testing.
Added additional trip helper to handle path corners differently (still needs testing).
> (refactor/feature) Fix server side tests. Add additional path helper

- client/src/components/App/App.jsx
- client/src/components/HeatMap/HeatMap.jsx
- client/src/components/utils/heatMapRadiusHelper.js
Added functionality to remove old heatmaps. Also cleaned up linting errors and wrote descriptive comments.
> (feature) Integrate HeatMap component (Closes #63)

- client/src/actions/index.js
- client/src/reducers/index.js
Conversion still in progress, but submitting PR to get code base and scaffolding up for others to use.
> (refactor) Build out action creators and reducers for redux conversion

- .gitignore
- client/package.json
- docker-compose.yml
- example.env
- integrationServer/package.json
- integrationServer/requestHandlers.js
- integrationServer/server.js
- integrationServer/spec/serverSpec.js
- launch.sh
- package.json
- riskService/assessmentWorker/worker.js
- riskService/config.js
- riskService/example.env
- riskService/package.json
- riskService/server.js
- tripService/package.json
This update moves all configuration to a .env file in the root folder. This enables the app to be launched with docker compose.
> (feature) Implement docker compose

- client/src/components/App/App.jsx
Still need to implement input field and give menu icon functionality
> (feature) Create toolbar to become a search bar (#93)

- client/src/components/App/App.jsx
Still need to write out callback function to handle a search query
> (feature) Implement search bar inside of toolbar (#93)

- client/src/actions/index.js
- client/src/components/App/App.jsx
- client/src/components/utils/appHelper.js
- client/src/containers/AppContainer/AppContainer.js
- client/src/index.js
Reimplemented functionality to get the user's current location once the map loads. My use of redux-thunk was not behaving as I thought it would, so I didn't use it. I used a callback instead.
> (refactor) Get current location (#93)

- client/src/components/App/App.css
- client/src/components/App/App.jsx
Additionally, added close button to Drawer and class toggle for Floating Action Button.
> (refactor) Replace Material UI Autocomplete with Google Places autocomplete (#93)

- integrationServer/requestHandlers.js
- tripService/spec/serverSpec.js
- tripService/tripHelpers.js
-begin integration
-update tripServer spec suite
> (fix) Integration

- client/public/index.html
- client/src/actions/index.js
- client/src/components/App/App.css
- client/src/components/App/App.jsx
- client/src/components/utils/appHelper.js
- client/src/containers/AppContainer/AppContainer.js
- client/src/index.js
- client/src/reducers/index.js
Also included:
- Selecting from displayed results
- Autofill search bar with current origin or destination (if it's been set)
- Change search results view based on whether searching for destination or origin
- Fix bug with menu drawer not opening in search view
> (feature) Dynamically display search results as user types

- client/src/components/App/App.jsx
- client/src/components/utils/appHelper.js
Also fixed:
Markers now render on map!
> (refactor) Convert origin and destination states to include lat/lng

- client/src/actions/index.js
- client/src/components/App/App.css
- client/src/components/App/App.jsx
- client/src/components/utils/appHelper.js
- client/src/containers/AppContainer/AppContainer.js
- client/src/reducers/index.js
Currently using a promise to return fake data after a GET request to the server.
_**Remove Promise in routeResponse action creator for production**_
> (fix) Make API call for directions on origin/destination submit

- client/src/components/App/App.jsx
Also updated prop types for new data format.
> (feature) Link directions button to window with google maps directions

- client/src/actions/index.js
Removed promise to provide fake data. Also corrected the server URL link and the data that will be stored in the store.
> (refactor) Use actual data response from server

- client/src/actions/index.js
- client/src/components/App/App.css
- client/src/components/App/App.jsx
- client/src/components/utils/appHelper.js
Also included:
- refactored to include a 'name' property of 'Current Location' if the current location is used as the origin
- removed appHelpers that are no longer needed
- show search results card only if there are search results
- change spacing between search cards
- add dividers to search results card
- change style of SELECTING_ROUTE toolbars and icon sizes
- factored out all styling that will be kept into the CSS file (textFieldInputStyle must be kept inside App.jsx because there is no way to reference without passing it in as a prop to the TextField component)
> (fix) Change current location text if not available

- client/src/components/App/App.jsx
- client/src/components/utils/appHelper.js
- client/src/index.js
Should have been displaying "Current location not available" when unable to locate the user.
Also included:
- changed the view the user gets taken to after closing the sidebar if both destination and origin has not been selected
- added PropTypes to resolve React alerts in console
> (fix) Fix bug with current location card display

- client/src/components/App/App.css
- client/src/components/App/App.jsx
- client/src/components/CancelRoutesButton/CancelRoutesButton.jsx
- client/src/components/utils/appHelper.js
Only change to the App.jsx file is to import this and add <CancelRoutesButton /> before the very last div closing tag in the render.
> (feature) Create cancel button

- client/src/components/App/App.jsx
- client/src/components/InfoWindow/InfoWindow.css
- client/src/components/InfoWindow/InfoWindow.jsx
Info window will display different information depending on whether it is the currently selected route
> (feature) Display info window over routes

- client/src/components/App/App.jsx
- client/src/components/InfoWindow/InfoWindow.css
- client/src/components/InfoWindow/InfoWindow.jsx
- client/src/components/utils/infoWindowHelpers.js
Also factored all utility functions used inside the InfoWindow component out into a separate file
> (fix) Display correct information in info window

- client/src/components/App/App.css
- client/src/components/App/App.jsx
- client/src/components/utils/appHelper.js
- client/src/index.js
Also displays different text in origin and destination toolbars if neither of them has been set
> (refactor) Do not send request if origin is not valid
